# Generated by Django 6.0.7 on 2026-07-16 02:12

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Mark as resolved once a moderator has reviewed this report.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube URL (watch, youtu.be, or shorts link)', validators=[movies.models.validate_youtube_url]),
        ),
    ]
