# Generated by Django 6.0.7 on 2026-07-16 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_reviewreport_resolved_alter_movie_trailer_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='movies.showschedule')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_reservation', to='movies.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
