# Generated by Django 6.0.7 on 2026-07-17 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_index_user_date_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text="City this theater is in, e.g. 'Mumbai'. Used for discovery filtering.", max_length=100),
        ),
        migrations.AlterField(
            model_name='theater',
            name='location',
            field=models.CharField(blank=True, help_text="Area/address within the city, e.g. 'Andheri West'.", max_length=255),
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='recently_viewed_user_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
