# Generated by Django 6.0.7 on 2026-07-17 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_theater_city_alter_theater_location_recentlyviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_emailed_at',
            field=models.DateTimeField(blank=True, help_text='Set once the ticket email has actually been sent (or last attempted).', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="Encoded in the ticket's QR code; lets staff verify a ticket without exposing the numeric order id alone.", unique=True),
        ),
        migrations.AddField(
            model_name='showschedule',
            name='screen',
            field=models.CharField(default='Screen 1', help_text='Screen/auditorium name, printed on the ticket.', max_length=50),
        ),
    ]
